services:
  - type: web
    name: telegram-discord-bot
    runtime: python
    buildCommand: pip install -r src/requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_KENTRIKO
        sync: false
      - key: WEBHOOK_EPIVIOSI
        sync: false
      - key: WEBHOOK_EFEDREIA
        sync: false
      - key: WEBHOOK_YGEIA
        sync: false
      - key: WEBHOOK_GEOPOLITIKA
        sync: false
