services:
  - type: web
    name: telegrambot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT src.main:app
    autoDeploy: true

