services:
  - type: web
    name: telegrambot
    env: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7514517889:AAHjBmv5LYplbLe182Quz8T1BKiWWwGdblc
      - key: DISCORD_WEBHOOK_URL
        value: https://discord.com/api/webhooks/1380237398268579870/fRHBfkGPSZWu7aqNVzeYkH7W6kab5ZDvPYaYLsl-YwaGUyidf8CgOBep8piDjnLWfGzs
    ports:
      - port: 10000
        protocol: http
