services:
  - type: web
    name: telegrambot
    env: python
    plan: free
    region: frankfurt
    buildCommand: ""
    startCommand: python src/main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_KENTRIKO
        sync: false
    autoDeploy: true

